import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`bg-slate-950 min-w-full min-h-screen flex flex-col items-center gap-10 overflow-hidden ${inter.className}`}
      >
        {children}
      </body>
    </html>
  );
}
